[package]

name = "pure_rust_csv_parser"
version = "0.0.1"
authors = [ "Your name <you@example.com>" ]

[[bin]]
name = "pure_rust_csv_parser"

[dependencies]
csv = "*"

[profile.release]
opt-level = 3
lto = true
